apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-client-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresql-client
  template:
    metadata:
      labels:
        io.kompose.service: postgresql-client
    spec:
      containers:
        - image: oad3jp999/postgresql-client:0.0.1
          name: postgresql-client
      restartPolicy: Always
