apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-server-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgresql-server
  template:
    metadata:
      labels:
        io.kompose.service: postgresql-server
    spec:
      containers:
        - image: oad3jp999/postgresql-server:0.0.1
          name: postgresql-server
          ports:
            - containerPort: 5432
      restartPolicy: Always
